services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env.production
    expose:
      - "9000"
    depends_on:
      - mysql
    volumes:
      # This app-code volume is used to share the application code between the app and nginx services without linking it to the host machine, which is
      # suitable for production environments but no mounting is more professional and secure for production environments.
      - app-code:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      # This app-code volume is used to share the application code between the app and nginx services without linking it to the host machine, which is
      # suitable for production environments but no mounting is more professional and secure for production environments.
      - app-code:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: edutrack
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  app-code:
