services:

  app:
    build:
      context: .
      target: app
    restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - laravel

  nginx:
    build:
      context: .
      target: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
