server {
    listen 80;
    server_name _;

    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # IMPORTANT: serve Vite assets directly
    location /build/ {
        root  /var/www/public/;
        access_log off;
        expires 1y;
    }
}

# server {
#     listen 80;
#    server_name _;

#     root /var/www/public;
#     index index.php index.html;

#     location / {
#        try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
#         include fastcgi_params;

#        fastcgi_pass app:9000;
#        fastcgi_index index.php;

#        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

#         fastcgi_read_timeout 300;
#     }

#    location ~ /\.ht {
#        deny all;
#     }
#    location /build/ {
#         alias /var/www/public/build/;
#        access_log off;
#         expires 1y;
#     }
# }
